CONFIG_ZMK_KEYBOARD_NAME="Silakka54"

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_NICE_VIEW_WIDGET_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

CONFIG_LV_Z_MEM_POOL_SIZE=16384

# Экспериментальные улучшения стабильности BLE
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Включаем поддержку ZMK Studio
CONFIG_ZMK_STUDIO=y

# Отключаем блокировку Studio (чтобы не нужно было нажимать специальную клавишу для входа)
CONFIG_ZMK_STUDIO_LOCKING=n